apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<aws account-id>:role/<role name>
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::<aws account-id>:user/user1
      username: user1
      groups:
        - system:masters
    - userarn: arn:aws:iam::<aws account-id>:user/user2
      username: user2
      groups:
        - readonly
